---
Author: "Zahlen Zbinden"
title: "Roy Kent Fucks"
date: "11-17-2023"
format: pdf
---
## Setup

```{r setup, include = FALSE}
library(ggplot2)
library(ggtext)
library(ggwordcloud)
library(showtext)
library(tidyverse)
```

## Load Data

```{r}
tuesdata <- tidytuesdayR::tt_load(2023, week = 39)
fuck <- tuesdata$richmondway
```

## Wrangle Data

```{r}
fuck_plot <- fuck |>
              select("Season_Episode", "F_count_RK", "Dating_flag", "Coaching_flag") |>
              mutate(word = "FUCK")

fuck_plot
```

## Load Fonts

```{r}
font_add_google("Oswald", "os")
showtext_auto()
plot_font <- "os"
```

## Plot

```{r}
#| warning: false
fp <- fuck_plot |>
        ggplot(aes(x = 0, y = 0, label = word, size = F_count_RK, color = Dating_flag)) +
          geom_text_wordcloud_area(
            aes(color = Dating_flag),
            eccentricity = .75,
            seed = 289,
            tstep = 0.04,
            family = "os",
            fontface = "bold",
            show.legend = TRUE,
            key_glyph = "text"
          ) +
          labs(
            caption = "Size based on number of FUCKS said by Roy Kent \n per episode of Ted Lasso "
          )+
          scale_size_area(max_size = 40) +
          scale_color_manual(
            labels = c("No", "Yea"), 
            values = c("black", "#e0218a"), 
            name = "Is Roy Dating Keeley?"
          ) +
          coord_cartesian(
            expand = FALSE
          )  +
          guides(
            size = "none",
            color = guide_legend(override.aes = list(label = "FUCK"))
          ) +
          theme(
            axis.text = element_blank(),
            axis.ticks = element_blank(),
            axis.title = element_blank(),
            legend.key = element_blank(),
            legend.margin = margin(0, 0, 0, 0),
            legend.position = c(0.5, .15),
            legend.text = element_text(size = 15, family = "os"),
            legend.title = element_text(size = 20, family = "os"),
            legend.title.align = 0.5,
            panel.background = element_blank(),
            panel.grid.major = element_blank(),
            panel.grid.minor = element_blank(),
            plot.background = element_rect(color = "white"),
            plot.caption = element_text(
              hjust = 0.5, 
              vjust = 30, 
              size = 10, 
              family = "os"
            ),
            plot.margin = margin(0, 0, 0, 0),
          )
fp
```
