---
author: "Zahlen Zbinden"
title: "Alone"
date: "11-19-2023"
format: "pdf"
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
    echo = TRUE,
    message = FALSE,
    warning = FALSE
)
library(ggplot2)
library(ggsankey)
library(ggtext)
library(pals)
library(RColorBrewer)
library(showtext)
library(tibble)
library(tidyverse)
library(viridis)
```

## Load Data

```{r}
survivalists <- readr::read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2023/2023-01-24/survivalists.csv')
```


## Fonts and Colors

```{r}
font_add_google("Caveat", "cave")
txt_font = "cave"

bg_col = "grey10"
txt_col = "white"
highlight_col = "grey40"
```

## Wrangle Data

```{r}
plt_data <- survivalists |>
              select("gender", "age", "reason_category", "result") |>
              mutate(reason_category = if_else(is.na(reason_category), "Winner", reason_category)) |>
              mutate(result = as.numeric(result)) |> 
              mutate(age_group = case_when(
                age <= 30 ~ "<30",
                age > 30 & age < 40 ~ "Thirties",
                age >= 40 & age < 50 ~ "Fourties",
                age >= 50 & age < 60 ~ "Fifties",
                age >= 60 ~ ">60"
              )) |>
              mutate(
                "Age Group" = age_group,
                "Reason for Leaving" = reason_category,
                "Gender" = gender,
                "Result" = result
              ) |>
              make_long("Age Group", "Reason for Leaving", "Gender", "Result") |>
              mutate(
                node = factor(node),
                node = fct_relevel(
                  node, 
                  c("10", "9", "8", "7", "6", "5", "4", "3", "2", "1")
                ),
                node = fct_relevel(
                  node, 
                  c(">60", "Fifties", "Fourties", "Thirties", "<30")
                )
              )
```


## Plot

```{r}
plt <- plt_data |>
          ggplot(
            aes(
              x = x,
              next_x = next_x,
              node = node,
              next_node = next_node,
              fill = factor(node),
              label = node
            )
          ) +
          geom_sankey(
            node.color = "white",
            flow.alpha = 0.8,
            linewidth = 0.25,
            color = "white"
          ) +
          geom_sankey_label(
            size = 7,
            color = "white",
            fill = highlight_col
          ) +
          labs(
            title = "Contestants on Alone",
            caption = "TidyTuesday 2023 week 4"
          ) +
          scale_fill_manual(values = unname(polychrome())) +
          theme(
            plot.title = element_text(
              family = txt_font, 
              size = 50,
              hjust = 0.5,
              vjust = 0.5,
              color = txt_col
            ),
            plot.caption = element_text(family = txt_font, color = "white", size = 15),
            plot.background = element_rect(fill = bg_col, color = bg_col),
            panel.background = element_rect(fill = bg_col, color = bg_col),
            panel.grid = element_blank(),
            axis.ticks = element_blank(),
            axis.title = element_blank(),
            axis.text.y = element_blank(),
            axis.text.x = element_text(
              family = txt_font,
              size = 40,
              color = txt_col
            ),
            legend.position = "none"
          ) 
plt
```


```{r}
ggsave("2023/2023-01-24/alone.png", plt, width = 7, height = 5)
```